sudo: required

services:
  - docker

before_install:
  - docker pull rocker/verse
  - docker run -d -p 127.0.0.1:80:4567 rocker/verse /bin/sh -c "cd ~; "
  - docker ps -a
  - docker run -ti rocker/verse /bin/sh -c "cd ~;"

install:
    - docker run -ti -v $(pwd):/home/rstudio/repo -w /home/rstudio/repo rocker/verse -e "source .build_tools/travis/install.sh"
script: 
    - docker run -ti -v $(pwd):/home/rstudio/repo -w /home/rstudio/repo rocker/verse -e "source .build_tools/travis/test_script.sh"
